### ISSUE TITLE
Add monochrome accent

### ISSUE THREAD

**Issue by oivva** [oivva/st-boxy#102]
Monochrome accent will be the same color as monochrome folders.

**Comment by musm** [comment]
What about also adding a white/light gray/dark gray/black accent option?  Is there a quick way to change the accent color using resource viewer in the mean time?

**Comment by oivva** [comment]
> What about also adding a white/light gray/dark gray/black accent option?

OK, I'll try to add mono accent (it will be pretty similar to those ones).
