### ISSUE TITLE
MagicPython

### ISSUE THREAD

**Issue by freshpotatoe** [oivva/st-boxy#119]
Any plans to support the nuances of this syntax highlighting theme?

**Comment by oivva** [comment]
Thanks! I have plans to add cursor and selection customization in 4.0.0. Any other requests? :wink:

**Comment by freshpotatoe** [comment]
It would be cool to have some complimentary themes eg, iterm colour schemes. However it would just go a long way to have the colours in the README.md so we could port it over more easily.

**Comment by oivva** [comment]
> It would be cool to have some complimentary themes eg, iterm colour schemes.
I have plans to do that, but with my own schemes (they will be available later).

> However it would just go a long way to have the colours in the README.md so we could port it over more easily.

Boxy color schemes are improved ST version of the:
- [Base16](https://github.com/chriskempson/base16) Yesterday & Tomorrow
- [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme)
- [Monokai Extended](https://github.com/jonschlinkert/sublime-monokai-extended)

So you can easily find the port for your environment.
