### ISSUE TITLE
Add option to always use accent color for the dirty state

### ISSUE THREAD

**Issue by hachesilva** [oivva/st-boxy#120]
FEATURE REQUEST

Add the ability to enable/disable the use of the accent color for dirty state icons.

Current behaviour:
Dirty state icon (pencil) is gray when dirty tab is not focused.
Dirty state icon is colored with accent color when dirty tab is focused.

Desired behaviour:
Dirty state icon is colored when dirty tab is not focused.
Dirty state icon is colored when dirty tab is focused.

**Comment by oivva** [comment]
Starting 3.6.0 you will be able to use `"theme_dirty_colored_always": true`.
