### ISSUE TITLE
Add option for quick panel border (like theme_popup_border_visible)

### ISSUE THREAD

**Issue by mattst** [oivva/st-boxy#122]
#### Enhancement Request

The very thin popup and autocomplete border which can be set with `theme_popup_border_visible` looks great.

I think the same style border would also look great on quick panels.

Would you consider adding `theme_quick_panel_border_visible` please?

Thanks.

**Comment by mattst** [comment]
Thanks oivva.

**Comment by oivva** [comment]
You're welcome when it'll be done :wink:

**Comment by mattst** [comment]
Oivva - wow, that looks great. Thanks so much, really appreciated.

I'm going to open a new issue in the next day or 2 proposing a new colour *accent* that I was playing around with over the weekend and that I would implement if you are interested. My test run looks great.

Cheers.
