### ISSUE TITLE
The `Boxy Configuration` option causes Sublime Text to crash.

### ISSUE THREAD

**Issue by toph-allen** [oivva/st-boxy#125]
Whenever I select `Boxy Configuration` from the Quick Panel menu, Sublime Text crashes.

#### Expected Behavior
When I select `Boxy Configuration`, the configuration menu should open.

#### Current Behavior
Sublime Text in its entirety crashes.

#### Steps to Reproduce (for bugs)

1. Open Quick Panel.
2. Select `Boxy Configuration`
3. Sublime Text crashes

Sometimes the main menu comes up, but any subsequent navigation causes it to crash.

#### Your Environment

macOS 10.12 (16A319)

**Comment by oivva** [comment]
This is related only to ST 3121 on macOS. 3122 should address the macOS crash. Try to update your Sublime Text.

**Comment by toph-allen** [comment]
Yep, that's correct.

**Comment by mikerockett** [comment]
Not sure if it's worth opening a new issue for this, but config doesn't open at all on 3114 fr me... Any ideas? (Other menus load, like extras and activation...)

**Comment by mikerockett** [comment]
Ah nevermind - default theme was in my ignore list... Removing it seems to have solved the problem.
