### ISSUE TITLE
Proposal for new accent colour, numix red

### ISSUE THREAD

**Issue by mattst** [oivva/st-boxy#126]
I've been working on a new colour *accent* for Boxy which uses the principal colour of the [Numix Project](http://satya164.github.io/numix/). The colour hex code is `#D64937` and the RGB is `[214, 73, 55]`, the colour info. page, [colorhexa.com](http://www.colorhexa.com/d64937), calls this colour 'moderate red', the *Numix Project* calls it 'Numix Red', I'd describe it as a 'reddy-brown' or a 'dirty-reddy-orange' - it is hard to categorize.

![numix_red](https://cloud.githubusercontent.com/assets/835623/18680088/23fe5ecc-7f5a-11e6-8e5e-4fd4a3f709ac.png)

*Numix Red* is already used as the principal colour of 4 Sublime Text themes available on *Package Control*:

- [Numix Theme](https://packagecontrol.io/packages/Numix%20Theme) 44k installs - uses Numix Red
- [Theme - Numix](https://packagecontrol.io/packages/Theme%20-%20Numix) 37k installs - uses Numix Red
- [Theme - Numix Light](https://packagecontrol.io/packages/Theme%20-%20Numix%20Light) 9k installs - uses Numix Red
- [Theme - Brogrammer](https://packagecontrol.io/packages/Theme%20-%20Brogrammer) 94k installs - uses colours very close to Numix Red

Although I like the colour, none of these themes satisfied my design requirements and I've been using *Predawn* for the last few years before I discovered *Boxy* a few weeks ago.

Here is how *Numix Red* would fit in with the existing *Boxy* colour *accents*:

![boxy_colour_chart](https://cloud.githubusercontent.com/assets/835623/18679854/449be650-7f59-11e6-9c69-ed0971de07b6.png)

Here's what I've done so far:

#### Image Conversion:

I used [Imagemagick](http://www.imagemagick.org/script/index.php) to convert all the button, scrollbar, sidebar, and tab images.

This was done by taking the images from the orange accent files and using a `Bash` script to convert them using the following commands:

```
# Orange accent to Numix:
convert "$in" -type TrueColorMatte -channel RGBA -fill "#D64937" -opaque "#F2683E" png32:"$out"

# Orange accent to Numix; shadow effect for the 6 'Atomized' expanded folder images:
convert "$in" -type TrueColorMatte -channel RGBA -fill "#A93223" -opaque "#C25332" png32:"$out"
```

There are 2 issues with the colour conversion:

- Size: The total size of all the Numix images is ~143k, the other accents are all ~77k, clearly my conversion script will need to be run again with a compression setting used.
- The 6 `button_selection_atomized_on` and `button_word_atomized_on` images need fixing. The different shade/opacity used on the edge of these in the Numix version retains the orange accent colour.

#### Boxy Tomorrow.sublime-theme:

I've added Numix entries throughout the `Boxy Tomorrow.sublime-theme` file - a copy of the file is in [this gist](https://gist.github.com/mattst/c7f160b7a373e13190e58b1baab70dc9).

To do this I worked through the file, copying each `tangerine` (a good word to search for) entry or section and converting the names, colour, and paths to Numix, before pasting the new entry or section back into the file beneath the tangerine entry or section.

While doing this I discovered that 2 additional colours were needed; 1 for the `label_control` on the `status_bar` and 1 for the `tab_label`. Here are the details of those entries:

Note that I am not 100% happy with the colours that I've chosen for these and will play around with some other colours.

```
Tangerine entry:

  {
    "class": "label_control",
    "settings": ["!theme_accent_mono", "theme_statusbar_colored", "theme_accent_tangerine"],
    "parents": [{"class": "status_bar"}],
    "color": [253, 237, 231]
  },

Numix entry:

  {
    "class": "label_control",
    "settings": ["!theme_accent_mono", "theme_statusbar_colored", "theme_accent_numix"],
    "parents": [{"class": "status_bar"}],
    "color": [251, 236, 234]
  },

Tangerine entry:

  {
    "class": "tab_label",
    "settings": ["!theme_accent_mono", "theme_bar_colored", "theme_accent_tangerine"],
    "fg": [250, 213, 199]
  },

Numix entry:

  {
    "class": "tab_label",
    "settings": ["!theme_accent_mono", "theme_bar_colored", "theme_accent_numix"],
    "fg": [246, 215, 213]
  },
```

#### Prototype:

What I have at the moment is a prototype. The screen capture image below is what `Boxy Tomorrow.sublime-theme` looks like with  `"theme_accent_numix": true`. I have also done a screen capture of the same window but with `"theme_accent_orange": true` - this is so that you can see that the Numix red *accent* is very different from the orange *accent* which is the closest in colour of the existing *accent* colour schemes.

Prototype of Boxy Tomorrow with Numix red accent:

![boxy_tomorrow_numix](https://cloud.githubusercontent.com/assets/835623/18679889/56618610-7f59-11e6-8900-8a5aa4a8ad03.png)

Boxy Tomorrow with the existing orange accent for comparison:

![boxy_tomorrow_orange](https://cloud.githubusercontent.com/assets/835623/18679929/7a2552c0-7f59-11e6-8fae-51cc04c0fcfd.png)

#### Going Forwards:

I have some questions:

- Most importantly: Would you like me to continue developing this? Clearly adding the Numix accent to `Boxy Monokai.sublime-theme`, `Boxy Ocean.sublime-theme`, and to `Boxy Yesterday.sublime-theme` will take quite a lot of work, so if you don't want the Numix accent then clearly I won't bother.

Assuming that the answer is "yes":

- Did you use *Imagemagick* to convert the button, scrollbar, sidebar, and tab images from one colour scheme to another? If so is there a better command line that I should use instead of the `convert` lines I used in the *Image Conversion* section above?

- What compression level would you like me to use when creating the `PNG` files?

- The `.src/settings/common.json` file will need a `numix` dictionary entry in the `accents` list. Am I correct in thinking that the `foreground` colour should be the same as the `tab_label` class colour in the `.sublime-theme` files and that the `highlighted` colour should be the same as the `label_control` class with the `status_bar` class `parents`? What exactly does this `accents` list control?

- Do you have any hints for choosing the `foreground` and `highlighted` colours? All I did was enter the Numix colour on [this page](http://www.w3schools.com/colors/colors_picker.asp) and I then chose colours at the lighter end of the list of the colours on the right of the page.

- Would you have any objection to my adding a Numix preset to `boxy_presets.py`?

I hope this all meets with your approval. Best wishes, mattst

**Comment by oivva** [comment]
> Would you like me to continue developing this?

Yes, of course. I like this accent very much.

> Did you use Imagemagick to convert the button, scrollbar, sidebar, and tab images from one colour scheme to another?

I use Photoshop with my own script for that. 

> If so is there a better command line that I should use instead of the convert lines I used in the Image Conversion section above?

> What compression level would you like me to use when creating the PNG files?

Currently, I don't know. The goal is to get good quality images. I can do the optimization from my side via `optimize:assets` task & some tweaks to [imagemin-optipng](https://github.com/imagemin/imagemin-optipng) package. Sublime Text doesn't like such options as [bitDepthReduction, colorTypeReduction, paletteReduction](https://github.com/imagemin/imagemin-optipng#bitdepthreduction)

> What exactly does this accents list control?
> Do you have any hints for choosing the foreground and highlighted colours?

Accent list controls some background & foreground colors in the theme. For `Numix` we will have next config:

```js
      {
        "id": "numix",
        "name": "Numix",
        "hex": "#d64937", // Numix HEX
        "rgb": "214, 73, 55", // Numix RGB
        "foreground": {
          "default": {
            "hex": "#f1bfb9",         // HEX Value of 65% Opacity White on Numix Background
            "rgb": "241, 191, 185" // RGB Value of 65% Opacity White on Numix Background
          },
          "highlighted": {
            "hex": "#f6d8d4",          // HEX Value of 85% Opacity White on Numix Background
            "rgb": "246, 216, 212"  // RGB Value of 85% Opacity White on Numix Background
          }
        }
      }
```

> `hex` and `rgb`

Mostly backgrounds of UI components when they are filled (E.g. `theme_bar_colored`, `theme_tab_selected_filled` & etc.).

> `foreground.default.hex` and `foreground.default.rgb`

Default foreground of the UI components when they are filled.

> `foreground.highlighted.hex` and `foreground.highlighted.rgb`

Foreground of the UI components when they are filled for `hover` and `selected` states.

> Would you have any objection to my adding a Numix preset to boxy_presets.py?

No, I love such a good contribution :wink: @mattst Thanks a lot!

**Comment by mattst** [comment]
Thanks for the info oivva - I will go ahead with the Numix colour scheme.

I noticed that you have altered the 4 `.sublime-theme` files in the latest commit `f5c8f1d` so I did a diff to see how best to change the work I've already done adding the Numix entries to `Boxy Tomorrow.sublime-theme`.

In doing that I noticed what I think is an error.

`Boxy Tomorrow.sublime-theme`, `Boxy Monokai.sublime-theme`, and `Boxy Ocean.sublime-theme` all contain the following entry at line 12209 but `Boxy Yesterday.sublime-theme` does not.

```
  {
    "class": "tab_close_button",
    "parents": [{"class": "tab_control", "attributes": ["selected"]}],
    "layer0.texture": "Boxy Theme/assets/variants/light/buttons/button_close.png"
  },
```

See here:

- [Line 12209: Boxy Tomorrow.sublime-theme](https://github.com/oivva/st-boxy/blob/dev/Boxy%20Tomorrow.sublime-theme#L12209)
- [Line 12209: Boxy Monokai.sublime-theme](https://github.com/oivva/st-boxy/blob/dev/Boxy%20Monokai.sublime-theme#L12209)
- [Line 12209: Boxy Ocean.sublime-theme](https://github.com/oivva/st-boxy/blob/dev/Boxy%20Ocean.sublime-theme#L12209)
- [Line 12209: Boxy Yesterday.sublime-theme](https://github.com/oivva/st-boxy/blob/dev/Boxy%20Yesterday.sublime-theme#L12209)

There may, of course, be a reason why  `Boxy Yesterday.sublime-theme` does not have this entry but I thought I'd let you know in case it is an error.

Hope this helps.

**Comment by oivva** [comment]
No, it's right behavior. You shouldn't change themes in the root folder. All themes should be generated from `.src/themes`. So if you want to add new accent you should change only `.src/settings/common.json` and add accent assets to `assets/numix`, then rebuild them via `gulp build:themes` task.

See [Building](https://github.com/oivva/st-boxy/blob/dev/.github/CONTRIBUTING.md#building).
