### ISSUE TITLE
Add "theme_tab_selected_overlined"

### ISSUE THREAD

**Issue by lllopo** [oivva/st-boxy#127]
Would be nice if we get also "theme_tab_selected_overlined" which adds a colored line on top of the active tab.
Another suggestion - maybe it would look better if with "theme_tab_selected_filled" the tab bar gets a colored bottom border.

**Comment by oivva** [comment]
> Would be nice if we get also "theme_tab_selected_overlined" which adds a colored line on top of the active tab.
> Another suggestion - maybe it would look better if with "theme_tab_selected_filled" the tab bar gets a colored bottom border.

Can you show me how it should look like, dirty painting or something else :wink:

**Comment by lllopo** [comment]
There you go (a bit quick and dirty). Hope you like 'em.
![filled](https://cloud.githubusercontent.com/assets/5485902/18711142/333c69c6-8011-11e6-8b35-c5c846c5dbc2.jpg)
![overline](https://cloud.githubusercontent.com/assets/5485902/18711141/333aa0aa-8011-11e6-8360-192535712851.jpg)

**Comment by oivva** [comment]
Looks very good, I'll add these options in 3.7.0 :wink:

**Comment by mattst** [comment]
That would be a nice addition.

The logical next steps would be:

`theme_tab_selected_postlined` - a vertical line on the right side of the tab to complement `theme_tab_selected_prelined` which places a vertical line on the left side of the tab:

![theme_tab_selected_postlined](https://cloud.githubusercontent.com/assets/835623/18988232/9c5c5004-86fd-11e6-873e-9cc9472af8b8.png)

`theme_tab_selected_horizontal_lined` - both `theme_tab_selected_underlined` and `theme_tab_selected_overlined`:

![theme_tab_selected_horizontal_lined](https://cloud.githubusercontent.com/assets/835623/18988249/a8219052-86fd-11e6-918c-7f01cafc22f9.png)

`theme_tab_selected_vertical_lined` - both `theme_tab_selected_prelined` and `theme_tab_selected_postlined`:

![theme_tab_selected_vertical_lined](https://cloud.githubusercontent.com/assets/835623/18988254/b1a84328-86fd-11e6-9237-af236ff17f13.png)

`theme_tab_selected_border_lined` - all of them to create a solid border:

![theme_tab_selected_border_lined](https://cloud.githubusercontent.com/assets/835623/18988262/bbaef22c-86fd-11e6-8521-b1dab17e1ae9.png)

Personally I think `theme_tab_selected_horizontal_lined` and `theme_tab_selected_border_lined` would be particularly effective.

What do you think?

**Comment by oivva** [comment]
@mattst It's hard to implement this because of Sublime Text layer number limitation (currently 4 layers). The only possible solution is to add complex texture but I don't like such idea. ST doesn't respect textures on HiDPI displays, details [here](https://forum.sublimetext.com/t/interface-suggestions/20828/87)

**Comment by mattst** [comment]
@oivva Okay, they were just possible additions that I thought of. I'm very happy with `theme_tab_selected_underlined`.

**Comment by michaelblyons** [comment]
I will definitely use the `overlined` option.

**Comment by mattst** [comment]
@oivva

Please note that in the `4.3 Tab Flavors` section of `Preferences.sublime-settings` you need to change the comments above `theme_tab_line_size_sm` and `theme_tab_line_size_lg` so that they read like this because you forgot to add `theme_tab_selected_overlined` to the comments.

```
  // Set size of the tab lines to small
  // When `theme_tab_selected_prelined`, `theme_tab_selected_underlined`
  // or `theme_tab_selected_overlined` is true
  "theme_tab_line_size_sm": false,

  // Set size of the tab lines to large
  // When `theme_tab_selected_prelined`, `theme_tab_selected_underlined`
  // or `theme_tab_selected_overlined` is true
  "theme_tab_line_size_lg": false,
```

HTH.

**Comment by oivva** [comment]
@mattst Ah, thanks :wink:
