### ISSUE TITLE
Please add 'Skins' support to your package.

### ISSUE THREAD

**Issue by deathaxe** [oivva/st-boxy#129]
_Skins_ is a plugin which intends to give users the ability to switch the whole UI with only one command.

This is basically the same as your "Boxy Theme: Activate" command but is meant to support all theme packages in general. The goal is to have all available themes and associated color schemes listed as skin in one quick panel.

Please add support for 'Skins' plugin by simply adding a file named like Boxy.skins to your package with the following content:
```
{
	"Boxy Yesterday":
	{
		"Preferences":
		{
			"theme": "Boxy Yesterday.sublime-theme",
			"color_scheme": "Packages/Boxy Theme/schemes/Boxy Yesterday.tmTheme"
		}
	},
	"Boxy Tomorrow":
	{
		"Preferences":
		{
			"theme": "Boxy Tomorrow.sublime-theme",
			"color_scheme": "Packages/Boxy Theme/schemes/Boxy Tomorrow.tmTheme"
		}
	},
	"Boxy Ocean":
	{
		"Preferences":
		{
			"theme": "Boxy Ocean.sublime-theme",
			"color_scheme": "Packages/Boxy Theme/schemes/Boxy Ocean.tmTheme"
		}
	},
	"Boxy Monokai":
	{
		"Preferences":
		{
			"theme": "Boxy Monokai.sublime-theme",
			"color_scheme": "Packages/Boxy Theme/schemes/Boxy Monokai.tmTheme"
		}
	},
}
```
Each theme entry must at least contain theme and color_scheme keys but can include more preferences, too.

For details see: [https://github.com/deathaxe/sublime-skins](https://github.com/deathaxe/sublime-skins)

**Comment by oivva** [comment]
No, problem. I'll add support of it in the next release :wink:

**Comment by deathaxe** [comment]
Cool, thanks.

**Comment by oivva** [comment]
I'll replace `Boxy Theme: Presets` with Skins package support.
