### ISSUE TITLE
Add settings for Console styling

### ISSUE THREAD

**Issue by bordaigorl** [oivva/st-boxy#130]
The console's styling is pretty flat at the moment.
It would be great to be able to control:

- font sizes
- contrast of the background/input panel
- borders

through theme settings.

**Comment by oivva** [comment]
You can change console font size via [this addon](https://packagecontrol.io/packages/Boxy%20Theme%20Addon%20-%20Widget%20Font%20Size).

> contrast of the background/input panel

It's hard to implement this with current approach. I have plans to create another theme in the near future which will add such functionality. But that's not the Boxy story, so sorry.

**Comment by bordaigorl** [comment]
Thanks for the reply! Too bad the console is so hard to distinguish wrt the other widgets!
Maybe if we make our voice heard...
Btw, Boxy is the best theme I've seen so far for Sublime. Keep up the great work!

**Comment by oivva** [comment]
This is my first theme, so there are many lessons learned. I have the vision how to make the theme even more hackable, however I'll do this with other theme, because of many breaking changes.
