### ISSUE TITLE
Option to remove rounded corners of text selection highlight

### ISSUE THREAD

**Issue by lllopo** [oivva/st-boxy#131]
I don't know if this is possible, but if so - would you add an option to choose between square and rounded selection highlight corners ?

**Comment by oivva** [comment]
It's impossible. See: https://forum.sublimetext.com/t/remove-rounded-corners-from-text-selection-highlights/4787/5?u=oivva

**Comment by lllopo** [comment]
Yeah, I found it later on, so sorry for bothering you with this. Pitty, though.
