### ISSUE TITLE
Tab overline setting is a non sequitur 

### ISSUE THREAD

**Issue by NoiSek** [oivva/st-boxy#133]
#### Expected Behavior
Adding  `"theme_tab_selected_overlined": true,` as referenced in the wiki to your Sublime Text settings should add a colored line to the top of each file tab.

Additionally, 'overlined' setting should show up in the Boxy configuration menu.

#### Current Behavior
- Adding  `"theme_tab_selected_overlined": true,` has no visible effect.
- Overlined is not accounted for the theme configuration.

#### Steps to Reproduce
1. Set theme to any Boxy subset.
2. Add `"theme_tab_selected_underlined": true,` to User Preferences.sublime-settings
3. Observe tab behavior
4. Replace `"theme_tab_selected_underlined": true,` with `"theme_tab_selected_overlined": true,`
5. Observe tab behavior

#### Environment
- Boxy Theme: 3.5.0
- Sublime Text: 3126
- Platform: windows
- Package Control: True
- Dependencies:
	* mdpopups: 1.10.0
	* markdown: 2.6.6
	* pygments: 2.1a0
	* jinja2: 2.8

**Comment by oivva** [comment]
Thanks :wink: Please wait a little bit. I've updated the docs, but 3.6.0 release will be available today.
