### ISSUE TITLE
Boxy accent colour chart

### ISSUE THREAD

**Issue by mattst** [oivva/st-boxy#134]
@oivva 

I was playing around with Imagemagick, which I used to convert the colours for the Numix accent, and produced this quite professional looking accent colour chart for Boxy.

Maybe you would like to use it in `README.md` and in the wiki.

Note: Github has auto-resized the image below so click on it to see the better quality original, although in my browser when I click the image to get it in a new tab I can't see the black edge 'trimming' so it would probably be better to save it instead.

![boxy_accent_colour_chart](https://cloud.githubusercontent.com/assets/835623/19186523/90684d80-8c7e-11e6-8824-a9e47d08aaba.png)

Hope this helps.

**Comment by oivva** [comment]
Oh, thanks :wink: I'll add it to the wiki, we already have very long README.md :smile:

**Comment by oivva** [comment]
Added, thanks again.

**Comment by mattst** [comment]
No problem.
