### ISSUE TITLE
Add `Boxy Nova` theme and colour scheme

### ISSUE THREAD

**Issue by dgrubelic** [oivva/st-boxy#137]
Just saw this Atom theme and colour scheme, it would be super awesome to see it as a theme in Boxy package.

http://www.trevordmiller.com/nova/

Thoughts?

**Comment by oivva** [comment]
@dgrubelic Wow, it looks awesome! I can add it, however it will be as typical `Boxy` scheme but with `Nova` colors. I don't want to change color scheme template to provide a dedicated color meaning introduced by this theme because many users like current implementation.

**Comment by dgrubelic** [comment]
Just out of curiosity, what changes would have to be made in Boxy theme to support Nova's dedicated colour meaning (don't really know what this means actually)? 

Honestly, i would be perfectly fine with Nova colours in Boxy just the it works now. I like current implementation, no need for changes. :)

Besides, one user (in this case me) can't really force you to change entire theme structure because of one colour scheme. :)

**Comment by oivva** [comment]
> Just out of curiosity, what changes would have to be made in Boxy theme to support Nova's dedicated colour meaning (don't really know what this means actually)?

I'm talking about this :smile: 

![1](https://cloud.githubusercontent.com/assets/9801624/19340375/4d792884-9131-11e6-9d6c-401ccde21da7.png)
![2](https://cloud.githubusercontent.com/assets/9801624/19340376/4d92eb5c-9131-11e6-95cd-0fc80dce5993.png)

It requires full color scheme rewrite :no_good_man: 

> Honestly, i would be perfectly fine with Nova colours in Boxy just the it works now. I like current implementation, no need for changes. :)

Ah, no problem, I'll add this theme in the next release :wink:

**Comment by dgrubelic** [comment]
> It requires full color scheme rewrite :no_good_man:

![how-about-no](https://cloud.githubusercontent.com/assets/1304876/19340777/d7404bda-912a-11e6-8fa1-7ac7838f06b2.jpg)

Thanks for including this into roadmap so fast. You are awesome! 😄

**Comment by dgrubelic** [comment]
Just a quick question.. When do you plan to release this theme? How soon will 5.0.0 be available to download? If you don't know, estimate is fine with me :)

**Comment by oivva** [comment]
It will be released right after closing [this pull request](https://github.com/wbond/package_control_channel/pull/5852) :wink:

**Comment by equinusocio** [comment]
Is a clone of my material theme..

**Comment by oivva** [comment]
@equinusocio [Nova](http://www.trevordmiller.com/nova/) is a clone of the `Material Theme`?

**Comment by equinusocio** [comment]
Yes, it use the identical color scheme..

**Comment by oivva** [comment]
![](http://i.imgur.com/Nyauf6b.png)

Left: Nova
Right: Material

**Comment by dgrubelic** [comment]
Well, you can't really say that this "identical"... They look pretty similar, this is true, but definitely not identical.

**Comment by equinusocio** [comment]
@oivva 
> so think you should not have to add this in your theme, for the same reason i told you to credit the Boxy Material Skin

**Comment by oivva** [comment]
@equinusocio I'm fully agree with you about the `Boxy Material Skin`, that's why I added note about that. However in this case, it's just Sublime Text version of `Nova`. You should tell its authors about copyright infringement, then I'll remove it from this package. 

Also I agree with @dgrubelic. They look pretty similar, but definitely not identical.

**Comment by dgrubelic** [comment]
@oivva can you please post `js` code compare of both colour schemes?

**Comment by equinusocio** [comment]
@oivva I'm not talking about copyright.. i'm talking about user experience, which I try to keep consistent. If the nova team decide to use a darkest background, we have a very very similar clone of material theme, inside your theme.

**Comment by oivva** [comment]
@dgrubelic ![](http://i.imgur.com/id7s1LB.png)

**Comment by equinusocio** [comment]
The only different thing is the color contrast..
> @oivva I'm not talking about copyright.. i'm talking about user experience, which I try to keep consistent. If the nova team decide to use a darkest background color, you will have a very very similar (UX) clone of material theme scheme (and skin) inside your boxy theme.

**Comment by equinusocio** [comment]
This is the material theme scheme, not that in the right side.
<img width="792" alt="screen shot 2016-10-17 at 11 14 00" src="https://cloud.githubusercontent.com/assets/10454741/19431962/ce497ca8-945a-11e6-9b8e-fec447bd3019.png">

**Comment by oivva** [comment]
> If the nova team decide to use a darkest background, we have a very very similar clone of material theme, inside your theme.

I don't have plans to add more themes or change colors of the existing ones. Even if the nova team decide to use a darkest background I won't change anything.

**Comment by oivva** [comment]
> This is the material theme scheme, not that in the right side.

How can I activate it? Is this colorscheme provided by `Material Theme` package?

**Comment by equinusocio** [comment]
Yes, is the **dafault** color scheme with the pure Javascript (not Babel) syntax

<img width="786" alt="screen shot 2016-10-17 at 11 18 15" src="https://cloud.githubusercontent.com/assets/10454741/19432120/6b9c68d0-945b-11e6-81a0-3b5f11d1724e.png">

**Comment by equinusocio** [comment]
> I don't have plans to add more themes or change colors of the existing ones. Even if the nova team decide to use a darkest background I won't change anything.

So is not a Nova integration..

**Comment by oivva** [comment]
@equinusocio Yes, this is its current state with `Boxy Template`, nothing more)

**Comment by oivva** [comment]
@equinusocio Look, it's nothing for me to remove it, because I don't use it. However some users such as @dgrubelic will love it. I just implement some popular schemes with my template. So if there're some problems with copyright infringement, I'll remove it. In other cases I think that `Material Theme` users know that they use.

**Comment by dgrubelic** [comment]
To be hones, I'm slightly confused with these colours, this is what official Nova color scheme looks like in Atom (pretty different colours):

<img width="611" alt="screen shot 2016-10-17 at 11 34 09" src="https://cloud.githubusercontent.com/assets/1304876/19432782/4724e89e-945e-11e6-8199-7d7984cb1051.png">

This screenshot looks totally different than posted above in JS file compare.

**Comment by dgrubelic** [comment]
As you can see, string color is #81c1c9, but in screenshot above psoted by @oivva it's #8fce93. Please tell me if i'm doing something wrong with color picking, but i just used these screenshots and picked color in Photoshop. They look totally different to me.

**Comment by equinusocio** [comment]
@dgrubelic @oivva just add Nova color palette to the Boxy template, the color combination is different.

**Comment by dgrubelic** [comment]
Yes, but if above screenshot posted by @oivva is current ST implementation of Nova color scheme, then colors are wrong since it looks totally different than the screenshot i just posted with Nova scheme in Atom.

**Comment by equinusocio** [comment]
If you use the color picker one the png file you will see a different color because the color profile. But i think the colors are the same

**Comment by dgrubelic** [comment]
Imho, i think that in case of string color, the "type" color from Nova is being used instead of "value/state" color (see @oivva second post for color names).

**Comment by dgrubelic** [comment]
I just tried switching every single available color profile on my Mac, and i must say, Nova string color definitely doesn't look like the one in @oivva's screenshot.

**Comment by oivva** [comment]
> To be hones, I'm slightly confused with these colours, this is what official Nova color scheme looks like in Atom (pretty different colours)

> This screenshot looks totally different than posted above in JS file compare.

Colors are the same, highlight differs. That's what I meant when said:

> It requires full color scheme rewrite

**Comment by equinusocio** [comment]
@oivva So I think that `feat: add Boxy Nova theme` can be misunderstood.. technically is a porting of the color palette (not schemes and themes)

**Comment by oivva** [comment]
@equinusocio Yes, you're right that's why I always add `Boxy` prefix, that means it's `Boxy` version of the color scheme and UI.

**Comment by equinusocio** [comment]
Oks 👍
