### ISSUE TITLE
No option for Boxy Nova ★ Minimal

### ISSUE THREAD

**Issue by mbarwick83** [oivva/st-boxy#140]
Trying to select **Boxy Nova ★ Minimal** skin..but it's not there. What am I missing here? I deleted Boxy package and re-installed. Nothing.

**Comment by oivva** [comment]
It will be available when 5.0.0 will be released. We are waiting for [this](https://github.com/wbond/package_control_channel/pull/5852).

**Comment by oivva** [comment]
It will be released tomorrow :wink:

**Comment by oivva** [comment]
I've published the release. It will be available approximately in two hours.
