### ISSUE TITLE
v5 broke a lot of icons, how can I revert to and lock in v4?

### ISSUE THREAD

**Issue by nickjj** [oivva/st-boxy#141]
I'm using the Linux version and it just auto-updated to v5.

It pretty much broke every file type icon.

Here's a before and after:

http://i.imgur.com/7vBb7fB.png

Is there a way to revert to the latest v4 release and disable auto-updates so I can continue using that version?

**Comment by oivva** [comment]
Just install [zz File Icons](https://github.com/oivva/st-file-icons). See [Icons](https://github.com/oivva/st-boxy#icons) section in the README.md.

**Comment by nickjj** [comment]
Confirmed fixed. Unless I missed it (very possible), I didn't see that come up in the changelog notification in Sublime.

**Comment by oivva** [comment]
Sorry :disappointed: I forgot to add this info to the changelog :neutral_face:
