### ISSUE TITLE
Feature request: Theme the position of the sidebar

### ISSUE THREAD

**Issue by nickjj** [oivva/st-boxy#142]
It would be really nice if you could choose to position the sidebar on either the left (default) or right side.

My thought process is, typically you stand in front of a monitor and read left to right. Having the sidebar on the right side will put the emphasis on your code, rather than the sidebar.

Is this feature something that could be implemented at the theme level and do you feel like it's a request worth pursuing?

**Comment by oivva** [comment]
Currently it isn't possible at all. I think you should open your issue [here](https://github.com/SublimeTextIssues/Core/issues).
