### ISSUE TITLE
Custom fonts reset after update

### ISSUE THREAD

**Issue by dezinerdudes** [oivva/st-boxy#143]
Great theme! However, after every theme update the custom font set in the Font Face addon is reset and lost. Am I doing something wrong or does the font need to be set again after every update?

**Comment by oivva** [comment]
@dezinerdudes Unfortunately, no, that's a known issue. However I have no plans to add more themes, so your last change will be relevant for a long time :wink:

**Comment by dezinerdudes** [comment]
Thank you for clarifying.
