### ISSUE TITLE
Lost sidebar icons on 5.0.0 upgrade

### ISSUE THREAD

**Issue by loicdtx** [oivva/st-boxy#144]
I lost the sidebar icons following today's update.

![screenshot from 2016-11-01 14-20-06](https://cloud.githubusercontent.com/assets/5638829/19891881/672df9ce-a042-11e6-8d67-b067f02ff812.png)

I tried uninstalling boxyTheme, deleting `~/.config/sublime-text-3/Cache` and `~/.config/sublime-text-3/Index` and deleting the `markupsafe`, `mdpopups`, `pygments`, `python-jinja2`, `python-markdown`  directories from `.config/sublime-text-3/Package`, but that didn't help.

## My environment

```
- Boxy Theme: 5.0.0
- Sublime Text: 3126
- Platform: linux
- Package Control: True
- Dependencies:
    * mdpopups: 1.10.0
    * markdown: 2.6.6
    * pygments: 2.1a0
    * jinja2: 2.8
```

### Other installed packages

```
Boxy Theme
Dockerfile Syntax Highlighting
Evernote
GitGutter
Git
LaTeX Word Count
Monokai Extended
Package Control
SideBarEnhancements
Table Cleaner
Table Editor
Virtualenv
WordCount
```

**Comment by oivva** [comment]
Just install [zz File Icons](https://github.com/oivva/st-file-icons). See [Icons](https://github.com/oivva/st-boxy#icons) section in the README.md.

**Comment by loicdtx** [comment]
That fixed it, thanks for the quick response.
