### ISSUE TITLE
Unreadable italic font on tabs on Windows

### ISSUE THREAD

**Issue by hsiktas** [oivva/st-boxy#146]
Peeking through files in my project folder without fully opening them for editing causes preview tabs with italic font. They look like this on my Mac.
![2016-11-11_19-09-41](https://cloud.githubusercontent.com/assets/4571159/20225408/6e1bb0b0-a843-11e6-8bef-961567499da9.png)

On Windows I get this instead:
![sublime_text_2016-11-11_19-10-39](https://cloud.githubusercontent.com/assets/4571159/20225421/864b9fe2-a843-11e6-8a58-676734aa9cba.png)

On both systems these are my settings:

```js
	"theme": "Boxy Tomorrow.sublime-theme",
	"theme_accent_numix": true,
	"theme_autocomplete_item_selected_colored": true,
	"theme_dropdown_atomized": true,
	"theme_find_panel_materialized": true,
	"theme_grid_border_size_xs": true,
	"theme_popup_border_visible": true,
	"theme_quick_panel_border_visible": true,
	"theme_quick_panel_item_selected_colored": true,
	"theme_scrollbar_colored": true,
	"theme_scrollbar_line": true,
	"theme_sidebar_disclosure": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_selected_underlined": true,
	"theme_tab_size_lg": true,
	"theme_unified": true,
```

I am using Hack as font_face but I don't think that this applies to the tabs. https://github.com/chrissimpkins/Hack

Is there something else I can try? I know that Sublime has more displaying issues on Windows than on macOS but I hope that this is not one of these bugs that can only be fixed by SublimeHQ. ☹

**Comment by oivva** [comment]
@hsiktas I think that's because you've installed [Boxy Theme Addon - Font Face](https://packagecontrol.io/packages/Boxy%20Theme%20Addon%20-%20Font%20Face) addon, but forgot to change the font family, or after the last update theme reverted it to the `Sans-Serif`. Just remove that addon or change the font family.

**Comment by hsiktas** [comment]
Thank you! I installed the font addon and forgot to adjust its settings.

Slightly offtopic: I just stumbled on this tool and it seems to decrease the huge differences between the font rendering of Windows and macOS: https://github.com/snowie2000/mactype

**Comment by oivva** [comment]
I'm the windows user, however I'm fully agree with you Mac font rendering much much better.
