### ISSUE TITLE
Add new themes

### ISSUE THREAD

**Issue by oivva** [oivva/st-boxy#88]
I have plans to implement just one more theme based on some popular color scheme. I need your help. Please give me your suggestions:

<**Link**>
<**Screenshot**>
<**Optional Info**>

 and vote for existing ones :wink: 

#### Expected Behavior

This theme will use colors of the winning color scheme, but with all Boxy goodies :heart:

**Comment by oivva** [comment]
**Boxy Cyanide**

Original: https://github.com/lefoy/cyanide-theme
Requested by @babygau in #24

**Comment by gerardroche** [comment]
Oh, it has to be solarized. Personally I use the Monokai scheme (and the boxy monokai theme is by far the best) and sometimes the solarized scheme.  The themes available for solarized are not particularly good.

http://ethanschoonover.com/solarized

![solarized-palette](https://cloud.githubusercontent.com/assets/44148/16686253/c69ac6c0-4508-11e6-935b-fd9d00899d8a.png)
![solarized-vim](https://cloud.githubusercontent.com/assets/44148/16686254/c69d3bee-4508-11e6-9262-7e621a87ba7b.png)

**Comment by dluzajic** [comment]
Maybe Facebook theme :)
[https://github.com/mbixby/facebook-color-scheme](url)

**Comment by oivva** [comment]
The voting is closed. I'll add `Solarized Dark & Light` themes in the 4.0.0. I have no plans to add more themes in the near future. That's why you are free to fork :wink:

**Comment by oivva** [comment]
Closed by 5293003795ce4350bb633514ccff44f42d8fedfa and ed123b7c93142ab80e12bbe0abae1a2301cd6628.
